import { build } from "esbuild";
import { readdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outdir = resolve(__dirname, "../../plugins/code/skills/design-inventory/scripts/dist");

const entries = readdirSync(resolve(__dirname, "src"))
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith("test-fixtures.ts"))
  .map((f) => resolve(__dirname, "src", f));

await build({
  entryPoints: entries,
  outdir,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  outExtension: { ".js": ".mjs" },
  banner: { js: "// Generated by build.mjs - do not edit; sources in src/" },
});
console.log(`built ${entries.length} entries to ${outdir}`);
