import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { buildBundles } from "../shared/build-bundles.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

await buildBundles({
  build,
  toolDir: __dirname,
  outdir: resolve(__dirname, "../../plugins/code/skills/design-inventory/scripts/dist"),
  isEntry: (f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith("test-fixtures.ts"),
  banner: "// Generated by build.mjs - do not edit; sources in src/",
});
