import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { buildBundles } from "../shared/build-bundles.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

await buildBundles({
  build,
  toolDir: __dirname,
  outdir: resolve(__dirname, "../../plugins/vibe/skills/guided-manual-qa/scripts/dist"),
  isEntry: (f) => f.endsWith(".ts") && !f.endsWith(".test.ts"),
  banner: "// Generated by build.mjs - do not edit; sources in tools/guided-manual-qa/src/",
});
