import { lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { dirname, join, sep } from "node:path";
import { MainSyncError, originFileSchema } from "./main-sync-contracts.js";
import { digest } from "./main-sync-state.js";
import { MAX_INPUT_BYTES } from "./main-sync-generated-input.js";
import type { z } from "zod";
import type { PackageOwner } from "./main-sync-contracts.js";

export type OriginFile = z.infer<typeof originFileSchema>;

/** Byte identity and Git-semantic regular mode, independent of the shell's incidental umask. */
export function originFile(root: string, file: string): OriginFile {
  const target = join(root, file);
  const stat = lstatSync(target);
  if (!stat.isFile() || stat.isSymbolicLink() || (stat.mode & 0o111) || stat.size > MAX_INPUT_BYTES
    || realpathSync(target) !== target) throw new MainSyncError(`Generated input must be a bounded canonical non-executable regular file: ${file}`, "NEEDS_CHANGE");
  for (let parent = dirname(target); parent !== root; parent = dirname(parent)) {
    if (!parent.startsWith(`${root}${sep}`) || lstatSync(parent).isSymbolicLink() || realpathSync(parent) !== parent) {
      throw new MainSyncError(`Generated input parent is not canonical: ${file}`, "NEEDS_CHANGE");
    }
  }
  return originFileSchema.parse({ path: file, bytes: stat.size, sha256: digest(readFileSync(target)), mode: "100644" });
}

/** Includes hidden producer metadata and rejects symlinked/extra special nodes before any consumption. */
export function originTree(root: string, path: string, allowed?: ReadonlySet<string>): OriginFile[] {
  const target = join(root, path);
  const stat = lstatSync(target, { throwIfNoEntry: false });
  if (!stat) return [];
  if (stat.isSymbolicLink() || realpathSync(target) !== target) throw new MainSyncError(`Generated output root cannot be a symlink or alias: ${path}`, "NEEDS_CHANGE");
  if (stat.isFile()) {
    if (allowed && !allowed.has(path)) throw new MainSyncError(`Unknown generated output must be preserved: ${path}`, "NEEDS_CHANGE");
    return [originFile(root, path)];
  }
  if (!stat.isDirectory()) throw new MainSyncError(`Generated output root is not regular: ${path}`, "NEEDS_CHANGE");
  if (allowed && ![...allowed].some((file) => file.startsWith(`${path}/`))) {
    throw new MainSyncError(`Unknown generated directory must be preserved: ${path}`, "NEEDS_CHANGE");
  }
  const entries = readdirSync(target).sort();
  const result: OriginFile[] = [];
  for (const name of entries) result.push(...originTree(root, `${path}/${name}`, allowed));
  if (result.length > 10000) throw new MainSyncError("Generated output set exceeds its finite bound", "NEEDS_CHANGE");
  return result;
}

export function sameOriginFiles(actual: OriginFile[], expected: OriginFile[]) {
  return JSON.stringify([...actual].sort(byPath)) === JSON.stringify([...expected].sort(byPath));
}

/** Changes to any consumed generated byte participate in the same immutable input identity. */
export function originIdentity(trackedSha: string, files: OriginFile[], packages: readonly PackageOwner[] = []) {
  return files.length || packages.length ? digest(JSON.stringify({ trackedSha, files: [...files].sort(byPath),
    packages: [...packages].sort((left, right) => byPath(left, right)) })) : trackedSha;
}

function byPath(left: { path: string }, right: { path: string }) { return left.path.localeCompare(right.path); }
