import { build } from "esbuild";
import { readdirSync } from "node:fs";

const entries = readdirSync("src")
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && !f.endsWith("test-fixtures.ts"))
  .map((f) => `src/${f}`);

await build({
  entryPoints: entries,
  outdir: "dist",
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  outExtension: { ".js": ".mjs" },
  banner: { js: "// Generated by build.mjs - do not edit; sources in src/" },
});
console.log(`built ${entries.length} entries to dist/`);
