import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { buildBundles } from "../shared/build-bundles.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Only CLI entry points are bundled. Library modules (pricing, transcript-cost)
// are reachable through the CLI bundle, so they are not emitted separately.
const CLI_ENTRIES = new Set(["cost-report.ts"]);

await buildBundles({
  build,
  toolDir: __dirname,
  outdir: resolve(__dirname, "../../plugins/code-review/scripts/dist"),
  isEntry: (f) => CLI_ENTRIES.has(f),
  banner: "// Generated by build.mjs - do not edit; sources in tools/code-review-cost/src/",
});
