import { build } from "esbuild";
import { readdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { resolve, dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outdir = resolve(__dirname, "../../plugins/code-review/scripts/dist");

// Clean stale bundles before building so renamed/deleted sources leave no orphans.
let cleaned = 0;
try {
  for (const f of readdirSync(outdir)) {
    if (f.endsWith(".mjs")) {
      rmSync(join(outdir, f));
      cleaned++;
    }
  }
} catch {
  // outdir may not exist yet on a fresh checkout; that's fine
}
if (cleaned > 0) {
  console.log(`cleaned ${cleaned} stale bundle(s) from ${outdir}`);
}

// Only CLI entry points are bundled. Library modules (pricing, transcript-cost)
// are reachable through the CLI bundle, so they are not emitted separately.
const CLI_ENTRIES = new Set(["cost-report.ts"]);
const entries = readdirSync(resolve(__dirname, "src"))
  .filter((f) => CLI_ENTRIES.has(f))
  .map((f) => resolve(__dirname, "src", f));

await build({
  entryPoints: entries,
  outdir,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node18",
  outExtension: { ".js": ".mjs" },
  banner: { js: "// Generated by build.mjs - do not edit; sources in tools/code-review-cost/src/" },
});
console.log(`built ${entries.length} entries to ${outdir}`);
