import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { buildBundles } from "../shared/build-bundles.mjs";

const toolDir = dirname(fileURLToPath(import.meta.url));
const outdir = resolve(toolDir, "../../plugins/vibe/skills/vibe/scripts/dist");
await buildBundles({
  build,
  toolDir,
  outdir,
  isEntry: (file) => ["writer-state.ts", "claude-worker.ts", "main-sync.ts"].includes(file),
  // The bundled compiler parser initializes its filesystem adapter using CommonJS path globals.
  banner: "// Generated by tools/vibe-workers/build.mjs; do not edit.\nimport { createRequire as __vibeRequire } from 'node:module'; import {fileURLToPath as __vibeFileURL} from 'node:url'; import {dirname as __vibeDir} from 'node:path'; const require = __vibeRequire(import.meta.url); const __filename = __vibeFileURL(import.meta.url); const __dirname = __vibeDir(__filename);",
});
// Preserve the bundled Apache notice while removing its upstream whitespace-only comment lines.
for (const name of readdirSync(outdir).filter((file) => file.endsWith(".mjs"))) {
  const path = resolve(outdir, name);
  const source = readFileSync(path, "utf8");
  const notice = source.lastIndexOf("/*! Bundled license information:");
  if (notice >= 0) writeFileSync(path, source.slice(0, notice) + source.slice(notice).split("\n").map((line) => line.trimEnd()).join("\n"));
}
