import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { buildBundles } from "../shared/build-bundles.mjs";

const toolDir = dirname(fileURLToPath(import.meta.url));
await buildBundles({
  build,
  toolDir,
  outdir: resolve(toolDir, "../../plugins/vibe/skills/vibe/scripts/dist"),
  isEntry: (file) => ["writer-state.ts", "claude-worker.ts"].includes(file),
  banner: "// Generated by tools/vibe-workers/build.mjs; do not edit.\nimport { createRequire } from 'node:module'; const require = createRequire(import.meta.url);",
});
